/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSubempreiteirosRouteImport } from './routes/_app/subempreiteiros'
import { Route as AppMotorClassificacaoRouteImport } from './routes/_app/motor-classificacao'
import { Route as AppDocumentosRouteImport } from './routes/_app/documentos'
import { Route as AppDecomposicaoPrecosRouteImport } from './routes/_app/decomposicao-precos'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBibliotecaMestraRouteImport } from './routes/_app/biblioteca-mestra'
import { Route as AppBibliotecaRouteImport } from './routes/_app/biblioteca'
import { Route as AppOrcamentosIndexRouteImport } from './routes/_app/orcamentos.index'
import { Route as AppObrasIndexRouteImport } from './routes/_app/obras.index'
import { Route as AppBibliotecaMestraIndexRouteImport } from './routes/_app/biblioteca-mestra.index'
import { Route as AppProcurementPacotesRouteImport } from './routes/_app/procurement.pacotes'
import { Route as AppOrcamentosDecomposicaoRouteImport } from './routes/_app/orcamentos.decomposicao'
import { Route as AppObrasIdRouteImport } from './routes/_app/obras.$id'
import { Route as AppBibliotecaMestraUnidadesRouteImport } from './routes/_app/biblioteca-mestra.unidades'
import { Route as AppBibliotecaMestraTemplatesRouteImport } from './routes/_app/biblioteca-mestra.templates'
import { Route as AppBibliotecaMestraSubespecialidadesRouteImport } from './routes/_app/biblioteca-mestra.subespecialidades'
import { Route as AppBibliotecaMestraSistemasRouteImport } from './routes/_app/biblioteca-mestra.sistemas'
import { Route as AppBibliotecaMestraKeywordsRouteImport } from './routes/_app/biblioteca-mestra.keywords'
import { Route as AppBibliotecaMestraEspecialidadesRouteImport } from './routes/_app/biblioteca-mestra.especialidades'
import { Route as AppBibliotecaMestraCategoriasRouteImport } from './routes/_app/biblioteca-mestra.categorias'
import { Route as AppBibliotecaMestraArtigosRouteImport } from './routes/_app/biblioteca-mestra.artigos'
import { Route as AppOrcamentosIdIndexRouteImport } from './routes/_app/orcamentos.$id.index'
import { Route as AppObrasIdIndexRouteImport } from './routes/_app/obras.$id.index'
import { Route as AppProcurementPacotesIdRouteImport } from './routes/_app/procurement.pacotes.$id'
import { Route as AppOrcamentosIdDecomposicaoRouteImport } from './routes/_app/orcamentos.$id.decomposicao'
import { Route as AppObrasIdRelatoriosRouteImport } from './routes/_app/obras.$id.relatorios'
import { Route as AppObrasIdProcurementRouteImport } from './routes/_app/obras.$id.procurement'
import { Route as AppObrasIdPlaneamentoRouteImport } from './routes/_app/obras.$id.planeamento'
import { Route as AppObrasIdOrcamentacaoRouteImport } from './routes/_app/obras.$id.orcamentacao'
import { Route as AppObrasIdMqRouteImport } from './routes/_app/obras.$id.mq'
import { Route as AppObrasIdMedicoesRouteImport } from './routes/_app/obras.$id.medicoes'
import { Route as AppObrasIdFinanceiraRouteImport } from './routes/_app/obras.$id.financeira'
import { Route as AppObrasIdDocumentosRouteImport } from './routes/_app/obras.$id.documentos'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubempreiteirosRoute = AppSubempreiteirosRouteImport.update({
  id: '/subempreiteiros',
  path: '/subempreiteiros',
  getParentRoute: () => AppRoute,
} as any)
const AppMotorClassificacaoRoute = AppMotorClassificacaoRouteImport.update({
  id: '/motor-classificacao',
  path: '/motor-classificacao',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosRoute = AppDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AppDecomposicaoPrecosRoute = AppDecomposicaoPrecosRouteImport.update({
  id: '/decomposicao-precos',
  path: '/decomposicao-precos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaMestraRoute = AppBibliotecaMestraRouteImport.update({
  id: '/biblioteca-mestra',
  path: '/biblioteca-mestra',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaRoute = AppBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosIndexRoute = AppOrcamentosIndexRouteImport.update({
  id: '/orcamentos/',
  path: '/orcamentos/',
  getParentRoute: () => AppRoute,
} as any)
const AppObrasIndexRoute = AppObrasIndexRouteImport.update({
  id: '/obras/',
  path: '/obras/',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaMestraIndexRoute =
  AppBibliotecaMestraIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppBibliotecaMestraRoute,
  } as any)
const AppProcurementPacotesRoute = AppProcurementPacotesRouteImport.update({
  id: '/procurement/pacotes',
  path: '/procurement/pacotes',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosDecomposicaoRoute =
  AppOrcamentosDecomposicaoRouteImport.update({
    id: '/orcamentos/decomposicao',
    path: '/orcamentos/decomposicao',
    getParentRoute: () => AppRoute,
  } as any)
const AppObrasIdRoute = AppObrasIdRouteImport.update({
  id: '/obras/$id',
  path: '/obras/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaMestraUnidadesRoute =
  AppBibliotecaMestraUnidadesRouteImport.update({
    id: '/unidades',
    path: '/unidades',
    getParentRoute: () => AppBibliotecaMestraRoute,
  } as any)
const AppBibliotecaMestraTemplatesRoute =
  AppBibliotecaMestraTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AppBibliotecaMestraRoute,
  } as any)
const AppBibliotecaMestraSubespecialidadesRoute =
  AppBibliotecaMestraSubespecialidadesRouteImport.update({
    id: '/subespecialidades',
    path: '/subespecialidades',
    getParentRoute: () => AppBibliotecaMestraRoute,
  } as any)
const AppBibliotecaMestraSistemasRoute =
  AppBibliotecaMestraSistemasRouteImport.update({
    id: '/sistemas',
    path: '/sistemas',
    getParentRoute: () => AppBibliotecaMestraRoute,
  } as any)
const AppBibliotecaMestraKeywordsRoute =
  AppBibliotecaMestraKeywordsRouteImport.update({
    id: '/keywords',
    path: '/keywords',
    getParentRoute: () => AppBibliotecaMestraRoute,
  } as any)
const AppBibliotecaMestraEspecialidadesRoute =
  AppBibliotecaMestraEspecialidadesRouteImport.update({
    id: '/especialidades',
    path: '/especialidades',
    getParentRoute: () => AppBibliotecaMestraRoute,
  } as any)
const AppBibliotecaMestraCategoriasRoute =
  AppBibliotecaMestraCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AppBibliotecaMestraRoute,
  } as any)
const AppBibliotecaMestraArtigosRoute =
  AppBibliotecaMestraArtigosRouteImport.update({
    id: '/artigos',
    path: '/artigos',
    getParentRoute: () => AppBibliotecaMestraRoute,
  } as any)
const AppOrcamentosIdIndexRoute = AppOrcamentosIdIndexRouteImport.update({
  id: '/orcamentos/$id/',
  path: '/orcamentos/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppObrasIdIndexRoute = AppObrasIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppObrasIdRoute,
} as any)
const AppProcurementPacotesIdRoute = AppProcurementPacotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProcurementPacotesRoute,
} as any)
const AppOrcamentosIdDecomposicaoRoute =
  AppOrcamentosIdDecomposicaoRouteImport.update({
    id: '/orcamentos/$id/decomposicao',
    path: '/orcamentos/$id/decomposicao',
    getParentRoute: () => AppRoute,
  } as any)
const AppObrasIdRelatoriosRoute = AppObrasIdRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppObrasIdRoute,
} as any)
const AppObrasIdProcurementRoute = AppObrasIdProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => AppObrasIdRoute,
} as any)
const AppObrasIdPlaneamentoRoute = AppObrasIdPlaneamentoRouteImport.update({
  id: '/planeamento',
  path: '/planeamento',
  getParentRoute: () => AppObrasIdRoute,
} as any)
const AppObrasIdOrcamentacaoRoute = AppObrasIdOrcamentacaoRouteImport.update({
  id: '/orcamentacao',
  path: '/orcamentacao',
  getParentRoute: () => AppObrasIdRoute,
} as any)
const AppObrasIdMqRoute = AppObrasIdMqRouteImport.update({
  id: '/mq',
  path: '/mq',
  getParentRoute: () => AppObrasIdRoute,
} as any)
const AppObrasIdMedicoesRoute = AppObrasIdMedicoesRouteImport.update({
  id: '/medicoes',
  path: '/medicoes',
  getParentRoute: () => AppObrasIdRoute,
} as any)
const AppObrasIdFinanceiraRoute = AppObrasIdFinanceiraRouteImport.update({
  id: '/financeira',
  path: '/financeira',
  getParentRoute: () => AppObrasIdRoute,
} as any)
const AppObrasIdDocumentosRoute = AppObrasIdDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AppObrasIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof AppBibliotecaRoute
  '/biblioteca-mestra': typeof AppBibliotecaMestraRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/decomposicao-precos': typeof AppDecomposicaoPrecosRoute
  '/documentos': typeof AppDocumentosRoute
  '/motor-classificacao': typeof AppMotorClassificacaoRoute
  '/subempreiteiros': typeof AppSubempreiteirosRoute
  '/biblioteca-mestra/artigos': typeof AppBibliotecaMestraArtigosRoute
  '/biblioteca-mestra/categorias': typeof AppBibliotecaMestraCategoriasRoute
  '/biblioteca-mestra/especialidades': typeof AppBibliotecaMestraEspecialidadesRoute
  '/biblioteca-mestra/keywords': typeof AppBibliotecaMestraKeywordsRoute
  '/biblioteca-mestra/sistemas': typeof AppBibliotecaMestraSistemasRoute
  '/biblioteca-mestra/subespecialidades': typeof AppBibliotecaMestraSubespecialidadesRoute
  '/biblioteca-mestra/templates': typeof AppBibliotecaMestraTemplatesRoute
  '/biblioteca-mestra/unidades': typeof AppBibliotecaMestraUnidadesRoute
  '/obras/$id': typeof AppObrasIdRouteWithChildren
  '/orcamentos/decomposicao': typeof AppOrcamentosDecomposicaoRoute
  '/procurement/pacotes': typeof AppProcurementPacotesRouteWithChildren
  '/biblioteca-mestra/': typeof AppBibliotecaMestraIndexRoute
  '/obras/': typeof AppObrasIndexRoute
  '/orcamentos/': typeof AppOrcamentosIndexRoute
  '/obras/$id/documentos': typeof AppObrasIdDocumentosRoute
  '/obras/$id/financeira': typeof AppObrasIdFinanceiraRoute
  '/obras/$id/medicoes': typeof AppObrasIdMedicoesRoute
  '/obras/$id/mq': typeof AppObrasIdMqRoute
  '/obras/$id/orcamentacao': typeof AppObrasIdOrcamentacaoRoute
  '/obras/$id/planeamento': typeof AppObrasIdPlaneamentoRoute
  '/obras/$id/procurement': typeof AppObrasIdProcurementRoute
  '/obras/$id/relatorios': typeof AppObrasIdRelatoriosRoute
  '/orcamentos/$id/decomposicao': typeof AppOrcamentosIdDecomposicaoRoute
  '/procurement/pacotes/$id': typeof AppProcurementPacotesIdRoute
  '/obras/$id/': typeof AppObrasIdIndexRoute
  '/orcamentos/$id/': typeof AppOrcamentosIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof AppBibliotecaRoute
  '/dashboard': typeof AppDashboardRoute
  '/decomposicao-precos': typeof AppDecomposicaoPrecosRoute
  '/documentos': typeof AppDocumentosRoute
  '/motor-classificacao': typeof AppMotorClassificacaoRoute
  '/subempreiteiros': typeof AppSubempreiteirosRoute
  '/biblioteca-mestra/artigos': typeof AppBibliotecaMestraArtigosRoute
  '/biblioteca-mestra/categorias': typeof AppBibliotecaMestraCategoriasRoute
  '/biblioteca-mestra/especialidades': typeof AppBibliotecaMestraEspecialidadesRoute
  '/biblioteca-mestra/keywords': typeof AppBibliotecaMestraKeywordsRoute
  '/biblioteca-mestra/sistemas': typeof AppBibliotecaMestraSistemasRoute
  '/biblioteca-mestra/subespecialidades': typeof AppBibliotecaMestraSubespecialidadesRoute
  '/biblioteca-mestra/templates': typeof AppBibliotecaMestraTemplatesRoute
  '/biblioteca-mestra/unidades': typeof AppBibliotecaMestraUnidadesRoute
  '/orcamentos/decomposicao': typeof AppOrcamentosDecomposicaoRoute
  '/procurement/pacotes': typeof AppProcurementPacotesRouteWithChildren
  '/biblioteca-mestra': typeof AppBibliotecaMestraIndexRoute
  '/obras': typeof AppObrasIndexRoute
  '/orcamentos': typeof AppOrcamentosIndexRoute
  '/obras/$id/documentos': typeof AppObrasIdDocumentosRoute
  '/obras/$id/financeira': typeof AppObrasIdFinanceiraRoute
  '/obras/$id/medicoes': typeof AppObrasIdMedicoesRoute
  '/obras/$id/mq': typeof AppObrasIdMqRoute
  '/obras/$id/orcamentacao': typeof AppObrasIdOrcamentacaoRoute
  '/obras/$id/planeamento': typeof AppObrasIdPlaneamentoRoute
  '/obras/$id/procurement': typeof AppObrasIdProcurementRoute
  '/obras/$id/relatorios': typeof AppObrasIdRelatoriosRoute
  '/orcamentos/$id/decomposicao': typeof AppOrcamentosIdDecomposicaoRoute
  '/procurement/pacotes/$id': typeof AppProcurementPacotesIdRoute
  '/obras/$id': typeof AppObrasIdIndexRoute
  '/orcamentos/$id': typeof AppOrcamentosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/biblioteca': typeof AppBibliotecaRoute
  '/_app/biblioteca-mestra': typeof AppBibliotecaMestraRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/decomposicao-precos': typeof AppDecomposicaoPrecosRoute
  '/_app/documentos': typeof AppDocumentosRoute
  '/_app/motor-classificacao': typeof AppMotorClassificacaoRoute
  '/_app/subempreiteiros': typeof AppSubempreiteirosRoute
  '/_app/biblioteca-mestra/artigos': typeof AppBibliotecaMestraArtigosRoute
  '/_app/biblioteca-mestra/categorias': typeof AppBibliotecaMestraCategoriasRoute
  '/_app/biblioteca-mestra/especialidades': typeof AppBibliotecaMestraEspecialidadesRoute
  '/_app/biblioteca-mestra/keywords': typeof AppBibliotecaMestraKeywordsRoute
  '/_app/biblioteca-mestra/sistemas': typeof AppBibliotecaMestraSistemasRoute
  '/_app/biblioteca-mestra/subespecialidades': typeof AppBibliotecaMestraSubespecialidadesRoute
  '/_app/biblioteca-mestra/templates': typeof AppBibliotecaMestraTemplatesRoute
  '/_app/biblioteca-mestra/unidades': typeof AppBibliotecaMestraUnidadesRoute
  '/_app/obras/$id': typeof AppObrasIdRouteWithChildren
  '/_app/orcamentos/decomposicao': typeof AppOrcamentosDecomposicaoRoute
  '/_app/procurement/pacotes': typeof AppProcurementPacotesRouteWithChildren
  '/_app/biblioteca-mestra/': typeof AppBibliotecaMestraIndexRoute
  '/_app/obras/': typeof AppObrasIndexRoute
  '/_app/orcamentos/': typeof AppOrcamentosIndexRoute
  '/_app/obras/$id/documentos': typeof AppObrasIdDocumentosRoute
  '/_app/obras/$id/financeira': typeof AppObrasIdFinanceiraRoute
  '/_app/obras/$id/medicoes': typeof AppObrasIdMedicoesRoute
  '/_app/obras/$id/mq': typeof AppObrasIdMqRoute
  '/_app/obras/$id/orcamentacao': typeof AppObrasIdOrcamentacaoRoute
  '/_app/obras/$id/planeamento': typeof AppObrasIdPlaneamentoRoute
  '/_app/obras/$id/procurement': typeof AppObrasIdProcurementRoute
  '/_app/obras/$id/relatorios': typeof AppObrasIdRelatoriosRoute
  '/_app/orcamentos/$id/decomposicao': typeof AppOrcamentosIdDecomposicaoRoute
  '/_app/procurement/pacotes/$id': typeof AppProcurementPacotesIdRoute
  '/_app/obras/$id/': typeof AppObrasIdIndexRoute
  '/_app/orcamentos/$id/': typeof AppOrcamentosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/biblioteca-mestra'
    | '/dashboard'
    | '/decomposicao-precos'
    | '/documentos'
    | '/motor-classificacao'
    | '/subempreiteiros'
    | '/biblioteca-mestra/artigos'
    | '/biblioteca-mestra/categorias'
    | '/biblioteca-mestra/especialidades'
    | '/biblioteca-mestra/keywords'
    | '/biblioteca-mestra/sistemas'
    | '/biblioteca-mestra/subespecialidades'
    | '/biblioteca-mestra/templates'
    | '/biblioteca-mestra/unidades'
    | '/obras/$id'
    | '/orcamentos/decomposicao'
    | '/procurement/pacotes'
    | '/biblioteca-mestra/'
    | '/obras/'
    | '/orcamentos/'
    | '/obras/$id/documentos'
    | '/obras/$id/financeira'
    | '/obras/$id/medicoes'
    | '/obras/$id/mq'
    | '/obras/$id/orcamentacao'
    | '/obras/$id/planeamento'
    | '/obras/$id/procurement'
    | '/obras/$id/relatorios'
    | '/orcamentos/$id/decomposicao'
    | '/procurement/pacotes/$id'
    | '/obras/$id/'
    | '/orcamentos/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/dashboard'
    | '/decomposicao-precos'
    | '/documentos'
    | '/motor-classificacao'
    | '/subempreiteiros'
    | '/biblioteca-mestra/artigos'
    | '/biblioteca-mestra/categorias'
    | '/biblioteca-mestra/especialidades'
    | '/biblioteca-mestra/keywords'
    | '/biblioteca-mestra/sistemas'
    | '/biblioteca-mestra/subespecialidades'
    | '/biblioteca-mestra/templates'
    | '/biblioteca-mestra/unidades'
    | '/orcamentos/decomposicao'
    | '/procurement/pacotes'
    | '/biblioteca-mestra'
    | '/obras'
    | '/orcamentos'
    | '/obras/$id/documentos'
    | '/obras/$id/financeira'
    | '/obras/$id/medicoes'
    | '/obras/$id/mq'
    | '/obras/$id/orcamentacao'
    | '/obras/$id/planeamento'
    | '/obras/$id/procurement'
    | '/obras/$id/relatorios'
    | '/orcamentos/$id/decomposicao'
    | '/procurement/pacotes/$id'
    | '/obras/$id'
    | '/orcamentos/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/biblioteca'
    | '/_app/biblioteca-mestra'
    | '/_app/dashboard'
    | '/_app/decomposicao-precos'
    | '/_app/documentos'
    | '/_app/motor-classificacao'
    | '/_app/subempreiteiros'
    | '/_app/biblioteca-mestra/artigos'
    | '/_app/biblioteca-mestra/categorias'
    | '/_app/biblioteca-mestra/especialidades'
    | '/_app/biblioteca-mestra/keywords'
    | '/_app/biblioteca-mestra/sistemas'
    | '/_app/biblioteca-mestra/subespecialidades'
    | '/_app/biblioteca-mestra/templates'
    | '/_app/biblioteca-mestra/unidades'
    | '/_app/obras/$id'
    | '/_app/orcamentos/decomposicao'
    | '/_app/procurement/pacotes'
    | '/_app/biblioteca-mestra/'
    | '/_app/obras/'
    | '/_app/orcamentos/'
    | '/_app/obras/$id/documentos'
    | '/_app/obras/$id/financeira'
    | '/_app/obras/$id/medicoes'
    | '/_app/obras/$id/mq'
    | '/_app/obras/$id/orcamentacao'
    | '/_app/obras/$id/planeamento'
    | '/_app/obras/$id/procurement'
    | '/_app/obras/$id/relatorios'
    | '/_app/orcamentos/$id/decomposicao'
    | '/_app/procurement/pacotes/$id'
    | '/_app/obras/$id/'
    | '/_app/orcamentos/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/subempreiteiros': {
      id: '/_app/subempreiteiros'
      path: '/subempreiteiros'
      fullPath: '/subempreiteiros'
      preLoaderRoute: typeof AppSubempreiteirosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/motor-classificacao': {
      id: '/_app/motor-classificacao'
      path: '/motor-classificacao'
      fullPath: '/motor-classificacao'
      preLoaderRoute: typeof AppMotorClassificacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documentos': {
      id: '/_app/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AppDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/decomposicao-precos': {
      id: '/_app/decomposicao-precos'
      path: '/decomposicao-precos'
      fullPath: '/decomposicao-precos'
      preLoaderRoute: typeof AppDecomposicaoPrecosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/biblioteca-mestra': {
      id: '/_app/biblioteca-mestra'
      path: '/biblioteca-mestra'
      fullPath: '/biblioteca-mestra'
      preLoaderRoute: typeof AppBibliotecaMestraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/biblioteca': {
      id: '/_app/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AppBibliotecaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamentos/': {
      id: '/_app/orcamentos/'
      path: '/orcamentos'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof AppOrcamentosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/obras/': {
      id: '/_app/obras/'
      path: '/obras'
      fullPath: '/obras/'
      preLoaderRoute: typeof AppObrasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/biblioteca-mestra/': {
      id: '/_app/biblioteca-mestra/'
      path: '/'
      fullPath: '/biblioteca-mestra/'
      preLoaderRoute: typeof AppBibliotecaMestraIndexRouteImport
      parentRoute: typeof AppBibliotecaMestraRoute
    }
    '/_app/procurement/pacotes': {
      id: '/_app/procurement/pacotes'
      path: '/procurement/pacotes'
      fullPath: '/procurement/pacotes'
      preLoaderRoute: typeof AppProcurementPacotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamentos/decomposicao': {
      id: '/_app/orcamentos/decomposicao'
      path: '/orcamentos/decomposicao'
      fullPath: '/orcamentos/decomposicao'
      preLoaderRoute: typeof AppOrcamentosDecomposicaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/obras/$id': {
      id: '/_app/obras/$id'
      path: '/obras/$id'
      fullPath: '/obras/$id'
      preLoaderRoute: typeof AppObrasIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/biblioteca-mestra/unidades': {
      id: '/_app/biblioteca-mestra/unidades'
      path: '/unidades'
      fullPath: '/biblioteca-mestra/unidades'
      preLoaderRoute: typeof AppBibliotecaMestraUnidadesRouteImport
      parentRoute: typeof AppBibliotecaMestraRoute
    }
    '/_app/biblioteca-mestra/templates': {
      id: '/_app/biblioteca-mestra/templates'
      path: '/templates'
      fullPath: '/biblioteca-mestra/templates'
      preLoaderRoute: typeof AppBibliotecaMestraTemplatesRouteImport
      parentRoute: typeof AppBibliotecaMestraRoute
    }
    '/_app/biblioteca-mestra/subespecialidades': {
      id: '/_app/biblioteca-mestra/subespecialidades'
      path: '/subespecialidades'
      fullPath: '/biblioteca-mestra/subespecialidades'
      preLoaderRoute: typeof AppBibliotecaMestraSubespecialidadesRouteImport
      parentRoute: typeof AppBibliotecaMestraRoute
    }
    '/_app/biblioteca-mestra/sistemas': {
      id: '/_app/biblioteca-mestra/sistemas'
      path: '/sistemas'
      fullPath: '/biblioteca-mestra/sistemas'
      preLoaderRoute: typeof AppBibliotecaMestraSistemasRouteImport
      parentRoute: typeof AppBibliotecaMestraRoute
    }
    '/_app/biblioteca-mestra/keywords': {
      id: '/_app/biblioteca-mestra/keywords'
      path: '/keywords'
      fullPath: '/biblioteca-mestra/keywords'
      preLoaderRoute: typeof AppBibliotecaMestraKeywordsRouteImport
      parentRoute: typeof AppBibliotecaMestraRoute
    }
    '/_app/biblioteca-mestra/especialidades': {
      id: '/_app/biblioteca-mestra/especialidades'
      path: '/especialidades'
      fullPath: '/biblioteca-mestra/especialidades'
      preLoaderRoute: typeof AppBibliotecaMestraEspecialidadesRouteImport
      parentRoute: typeof AppBibliotecaMestraRoute
    }
    '/_app/biblioteca-mestra/categorias': {
      id: '/_app/biblioteca-mestra/categorias'
      path: '/categorias'
      fullPath: '/biblioteca-mestra/categorias'
      preLoaderRoute: typeof AppBibliotecaMestraCategoriasRouteImport
      parentRoute: typeof AppBibliotecaMestraRoute
    }
    '/_app/biblioteca-mestra/artigos': {
      id: '/_app/biblioteca-mestra/artigos'
      path: '/artigos'
      fullPath: '/biblioteca-mestra/artigos'
      preLoaderRoute: typeof AppBibliotecaMestraArtigosRouteImport
      parentRoute: typeof AppBibliotecaMestraRoute
    }
    '/_app/orcamentos/$id/': {
      id: '/_app/orcamentos/$id/'
      path: '/orcamentos/$id'
      fullPath: '/orcamentos/$id/'
      preLoaderRoute: typeof AppOrcamentosIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/obras/$id/': {
      id: '/_app/obras/$id/'
      path: '/'
      fullPath: '/obras/$id/'
      preLoaderRoute: typeof AppObrasIdIndexRouteImport
      parentRoute: typeof AppObrasIdRoute
    }
    '/_app/procurement/pacotes/$id': {
      id: '/_app/procurement/pacotes/$id'
      path: '/$id'
      fullPath: '/procurement/pacotes/$id'
      preLoaderRoute: typeof AppProcurementPacotesIdRouteImport
      parentRoute: typeof AppProcurementPacotesRoute
    }
    '/_app/orcamentos/$id/decomposicao': {
      id: '/_app/orcamentos/$id/decomposicao'
      path: '/orcamentos/$id/decomposicao'
      fullPath: '/orcamentos/$id/decomposicao'
      preLoaderRoute: typeof AppOrcamentosIdDecomposicaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/obras/$id/relatorios': {
      id: '/_app/obras/$id/relatorios'
      path: '/relatorios'
      fullPath: '/obras/$id/relatorios'
      preLoaderRoute: typeof AppObrasIdRelatoriosRouteImport
      parentRoute: typeof AppObrasIdRoute
    }
    '/_app/obras/$id/procurement': {
      id: '/_app/obras/$id/procurement'
      path: '/procurement'
      fullPath: '/obras/$id/procurement'
      preLoaderRoute: typeof AppObrasIdProcurementRouteImport
      parentRoute: typeof AppObrasIdRoute
    }
    '/_app/obras/$id/planeamento': {
      id: '/_app/obras/$id/planeamento'
      path: '/planeamento'
      fullPath: '/obras/$id/planeamento'
      preLoaderRoute: typeof AppObrasIdPlaneamentoRouteImport
      parentRoute: typeof AppObrasIdRoute
    }
    '/_app/obras/$id/orcamentacao': {
      id: '/_app/obras/$id/orcamentacao'
      path: '/orcamentacao'
      fullPath: '/obras/$id/orcamentacao'
      preLoaderRoute: typeof AppObrasIdOrcamentacaoRouteImport
      parentRoute: typeof AppObrasIdRoute
    }
    '/_app/obras/$id/mq': {
      id: '/_app/obras/$id/mq'
      path: '/mq'
      fullPath: '/obras/$id/mq'
      preLoaderRoute: typeof AppObrasIdMqRouteImport
      parentRoute: typeof AppObrasIdRoute
    }
    '/_app/obras/$id/medicoes': {
      id: '/_app/obras/$id/medicoes'
      path: '/medicoes'
      fullPath: '/obras/$id/medicoes'
      preLoaderRoute: typeof AppObrasIdMedicoesRouteImport
      parentRoute: typeof AppObrasIdRoute
    }
    '/_app/obras/$id/financeira': {
      id: '/_app/obras/$id/financeira'
      path: '/financeira'
      fullPath: '/obras/$id/financeira'
      preLoaderRoute: typeof AppObrasIdFinanceiraRouteImport
      parentRoute: typeof AppObrasIdRoute
    }
    '/_app/obras/$id/documentos': {
      id: '/_app/obras/$id/documentos'
      path: '/documentos'
      fullPath: '/obras/$id/documentos'
      preLoaderRoute: typeof AppObrasIdDocumentosRouteImport
      parentRoute: typeof AppObrasIdRoute
    }
  }
}

interface AppBibliotecaMestraRouteChildren {
  AppBibliotecaMestraArtigosRoute: typeof AppBibliotecaMestraArtigosRoute
  AppBibliotecaMestraCategoriasRoute: typeof AppBibliotecaMestraCategoriasRoute
  AppBibliotecaMestraEspecialidadesRoute: typeof AppBibliotecaMestraEspecialidadesRoute
  AppBibliotecaMestraKeywordsRoute: typeof AppBibliotecaMestraKeywordsRoute
  AppBibliotecaMestraSistemasRoute: typeof AppBibliotecaMestraSistemasRoute
  AppBibliotecaMestraSubespecialidadesRoute: typeof AppBibliotecaMestraSubespecialidadesRoute
  AppBibliotecaMestraTemplatesRoute: typeof AppBibliotecaMestraTemplatesRoute
  AppBibliotecaMestraUnidadesRoute: typeof AppBibliotecaMestraUnidadesRoute
  AppBibliotecaMestraIndexRoute: typeof AppBibliotecaMestraIndexRoute
}

const AppBibliotecaMestraRouteChildren: AppBibliotecaMestraRouteChildren = {
  AppBibliotecaMestraArtigosRoute: AppBibliotecaMestraArtigosRoute,
  AppBibliotecaMestraCategoriasRoute: AppBibliotecaMestraCategoriasRoute,
  AppBibliotecaMestraEspecialidadesRoute:
    AppBibliotecaMestraEspecialidadesRoute,
  AppBibliotecaMestraKeywordsRoute: AppBibliotecaMestraKeywordsRoute,
  AppBibliotecaMestraSistemasRoute: AppBibliotecaMestraSistemasRoute,
  AppBibliotecaMestraSubespecialidadesRoute:
    AppBibliotecaMestraSubespecialidadesRoute,
  AppBibliotecaMestraTemplatesRoute: AppBibliotecaMestraTemplatesRoute,
  AppBibliotecaMestraUnidadesRoute: AppBibliotecaMestraUnidadesRoute,
  AppBibliotecaMestraIndexRoute: AppBibliotecaMestraIndexRoute,
}

const AppBibliotecaMestraRouteWithChildren =
  AppBibliotecaMestraRoute._addFileChildren(AppBibliotecaMestraRouteChildren)

interface AppObrasIdRouteChildren {
  AppObrasIdDocumentosRoute: typeof AppObrasIdDocumentosRoute
  AppObrasIdFinanceiraRoute: typeof AppObrasIdFinanceiraRoute
  AppObrasIdMedicoesRoute: typeof AppObrasIdMedicoesRoute
  AppObrasIdMqRoute: typeof AppObrasIdMqRoute
  AppObrasIdOrcamentacaoRoute: typeof AppObrasIdOrcamentacaoRoute
  AppObrasIdPlaneamentoRoute: typeof AppObrasIdPlaneamentoRoute
  AppObrasIdProcurementRoute: typeof AppObrasIdProcurementRoute
  AppObrasIdRelatoriosRoute: typeof AppObrasIdRelatoriosRoute
  AppObrasIdIndexRoute: typeof AppObrasIdIndexRoute
}

const AppObrasIdRouteChildren: AppObrasIdRouteChildren = {
  AppObrasIdDocumentosRoute: AppObrasIdDocumentosRoute,
  AppObrasIdFinanceiraRoute: AppObrasIdFinanceiraRoute,
  AppObrasIdMedicoesRoute: AppObrasIdMedicoesRoute,
  AppObrasIdMqRoute: AppObrasIdMqRoute,
  AppObrasIdOrcamentacaoRoute: AppObrasIdOrcamentacaoRoute,
  AppObrasIdPlaneamentoRoute: AppObrasIdPlaneamentoRoute,
  AppObrasIdProcurementRoute: AppObrasIdProcurementRoute,
  AppObrasIdRelatoriosRoute: AppObrasIdRelatoriosRoute,
  AppObrasIdIndexRoute: AppObrasIdIndexRoute,
}

const AppObrasIdRouteWithChildren = AppObrasIdRoute._addFileChildren(
  AppObrasIdRouteChildren,
)

interface AppProcurementPacotesRouteChildren {
  AppProcurementPacotesIdRoute: typeof AppProcurementPacotesIdRoute
}

const AppProcurementPacotesRouteChildren: AppProcurementPacotesRouteChildren = {
  AppProcurementPacotesIdRoute: AppProcurementPacotesIdRoute,
}

const AppProcurementPacotesRouteWithChildren =
  AppProcurementPacotesRoute._addFileChildren(
    AppProcurementPacotesRouteChildren,
  )

interface AppRouteChildren {
  AppBibliotecaRoute: typeof AppBibliotecaRoute
  AppBibliotecaMestraRoute: typeof AppBibliotecaMestraRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDecomposicaoPrecosRoute: typeof AppDecomposicaoPrecosRoute
  AppDocumentosRoute: typeof AppDocumentosRoute
  AppMotorClassificacaoRoute: typeof AppMotorClassificacaoRoute
  AppSubempreiteirosRoute: typeof AppSubempreiteirosRoute
  AppObrasIdRoute: typeof AppObrasIdRouteWithChildren
  AppOrcamentosDecomposicaoRoute: typeof AppOrcamentosDecomposicaoRoute
  AppProcurementPacotesRoute: typeof AppProcurementPacotesRouteWithChildren
  AppObrasIndexRoute: typeof AppObrasIndexRoute
  AppOrcamentosIndexRoute: typeof AppOrcamentosIndexRoute
  AppOrcamentosIdDecomposicaoRoute: typeof AppOrcamentosIdDecomposicaoRoute
  AppOrcamentosIdIndexRoute: typeof AppOrcamentosIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBibliotecaRoute: AppBibliotecaRoute,
  AppBibliotecaMestraRoute: AppBibliotecaMestraRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDecomposicaoPrecosRoute: AppDecomposicaoPrecosRoute,
  AppDocumentosRoute: AppDocumentosRoute,
  AppMotorClassificacaoRoute: AppMotorClassificacaoRoute,
  AppSubempreiteirosRoute: AppSubempreiteirosRoute,
  AppObrasIdRoute: AppObrasIdRouteWithChildren,
  AppOrcamentosDecomposicaoRoute: AppOrcamentosDecomposicaoRoute,
  AppProcurementPacotesRoute: AppProcurementPacotesRouteWithChildren,
  AppObrasIndexRoute: AppObrasIndexRoute,
  AppOrcamentosIndexRoute: AppOrcamentosIndexRoute,
  AppOrcamentosIdDecomposicaoRoute: AppOrcamentosIdDecomposicaoRoute,
  AppOrcamentosIdIndexRoute: AppOrcamentosIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
