/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSubempreiteirosRouteImport } from './routes/_app/subempreiteiros'
import { Route as AppObrasRouteImport } from './routes/_app/obras'
import { Route as AppDocumentosRouteImport } from './routes/_app/documentos'
import { Route as AppDecomposicaoPrecosRouteImport } from './routes/_app/decomposicao-precos'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBibliotecaRouteImport } from './routes/_app/biblioteca'
import { Route as AppOrcamentosIndexRouteImport } from './routes/_app/orcamentos.index'
import { Route as AppOrcamentosDecomposicaoRouteImport } from './routes/_app/orcamentos.decomposicao'
import { Route as AppOrcamentosIdIndexRouteImport } from './routes/_app/orcamentos.$id.index'
import { Route as AppOrcamentosIdDecomposicaoRouteImport } from './routes/_app/orcamentos.$id.decomposicao'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubempreiteirosRoute = AppSubempreiteirosRouteImport.update({
  id: '/subempreiteiros',
  path: '/subempreiteiros',
  getParentRoute: () => AppRoute,
} as any)
const AppObrasRoute = AppObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosRoute = AppDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AppDecomposicaoPrecosRoute = AppDecomposicaoPrecosRouteImport.update({
  id: '/decomposicao-precos',
  path: '/decomposicao-precos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBibliotecaRoute = AppBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosIndexRoute = AppOrcamentosIndexRouteImport.update({
  id: '/orcamentos/',
  path: '/orcamentos/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosDecomposicaoRoute =
  AppOrcamentosDecomposicaoRouteImport.update({
    id: '/orcamentos/decomposicao',
    path: '/orcamentos/decomposicao',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrcamentosIdIndexRoute = AppOrcamentosIdIndexRouteImport.update({
  id: '/orcamentos/$id/',
  path: '/orcamentos/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosIdDecomposicaoRoute =
  AppOrcamentosIdDecomposicaoRouteImport.update({
    id: '/orcamentos/$id/decomposicao',
    path: '/orcamentos/$id/decomposicao',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof AppBibliotecaRoute
  '/dashboard': typeof AppDashboardRoute
  '/decomposicao-precos': typeof AppDecomposicaoPrecosRoute
  '/documentos': typeof AppDocumentosRoute
  '/obras': typeof AppObrasRoute
  '/subempreiteiros': typeof AppSubempreiteirosRoute
  '/orcamentos/decomposicao': typeof AppOrcamentosDecomposicaoRoute
  '/orcamentos/': typeof AppOrcamentosIndexRoute
  '/orcamentos/$id/decomposicao': typeof AppOrcamentosIdDecomposicaoRoute
  '/orcamentos/$id/': typeof AppOrcamentosIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof AppBibliotecaRoute
  '/dashboard': typeof AppDashboardRoute
  '/decomposicao-precos': typeof AppDecomposicaoPrecosRoute
  '/documentos': typeof AppDocumentosRoute
  '/obras': typeof AppObrasRoute
  '/subempreiteiros': typeof AppSubempreiteirosRoute
  '/orcamentos/decomposicao': typeof AppOrcamentosDecomposicaoRoute
  '/orcamentos': typeof AppOrcamentosIndexRoute
  '/orcamentos/$id/decomposicao': typeof AppOrcamentosIdDecomposicaoRoute
  '/orcamentos/$id': typeof AppOrcamentosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/biblioteca': typeof AppBibliotecaRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/decomposicao-precos': typeof AppDecomposicaoPrecosRoute
  '/_app/documentos': typeof AppDocumentosRoute
  '/_app/obras': typeof AppObrasRoute
  '/_app/subempreiteiros': typeof AppSubempreiteirosRoute
  '/_app/orcamentos/decomposicao': typeof AppOrcamentosDecomposicaoRoute
  '/_app/orcamentos/': typeof AppOrcamentosIndexRoute
  '/_app/orcamentos/$id/decomposicao': typeof AppOrcamentosIdDecomposicaoRoute
  '/_app/orcamentos/$id/': typeof AppOrcamentosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/dashboard'
    | '/decomposicao-precos'
    | '/documentos'
    | '/obras'
    | '/subempreiteiros'
    | '/orcamentos/decomposicao'
    | '/orcamentos/'
    | '/orcamentos/$id/decomposicao'
    | '/orcamentos/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/dashboard'
    | '/decomposicao-precos'
    | '/documentos'
    | '/obras'
    | '/subempreiteiros'
    | '/orcamentos/decomposicao'
    | '/orcamentos'
    | '/orcamentos/$id/decomposicao'
    | '/orcamentos/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/biblioteca'
    | '/_app/dashboard'
    | '/_app/decomposicao-precos'
    | '/_app/documentos'
    | '/_app/obras'
    | '/_app/subempreiteiros'
    | '/_app/orcamentos/decomposicao'
    | '/_app/orcamentos/'
    | '/_app/orcamentos/$id/decomposicao'
    | '/_app/orcamentos/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/subempreiteiros': {
      id: '/_app/subempreiteiros'
      path: '/subempreiteiros'
      fullPath: '/subempreiteiros'
      preLoaderRoute: typeof AppSubempreiteirosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/obras': {
      id: '/_app/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof AppObrasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documentos': {
      id: '/_app/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AppDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/decomposicao-precos': {
      id: '/_app/decomposicao-precos'
      path: '/decomposicao-precos'
      fullPath: '/decomposicao-precos'
      preLoaderRoute: typeof AppDecomposicaoPrecosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/biblioteca': {
      id: '/_app/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AppBibliotecaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamentos/': {
      id: '/_app/orcamentos/'
      path: '/orcamentos'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof AppOrcamentosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamentos/decomposicao': {
      id: '/_app/orcamentos/decomposicao'
      path: '/orcamentos/decomposicao'
      fullPath: '/orcamentos/decomposicao'
      preLoaderRoute: typeof AppOrcamentosDecomposicaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamentos/$id/': {
      id: '/_app/orcamentos/$id/'
      path: '/orcamentos/$id'
      fullPath: '/orcamentos/$id/'
      preLoaderRoute: typeof AppOrcamentosIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamentos/$id/decomposicao': {
      id: '/_app/orcamentos/$id/decomposicao'
      path: '/orcamentos/$id/decomposicao'
      fullPath: '/orcamentos/$id/decomposicao'
      preLoaderRoute: typeof AppOrcamentosIdDecomposicaoRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBibliotecaRoute: typeof AppBibliotecaRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDecomposicaoPrecosRoute: typeof AppDecomposicaoPrecosRoute
  AppDocumentosRoute: typeof AppDocumentosRoute
  AppObrasRoute: typeof AppObrasRoute
  AppSubempreiteirosRoute: typeof AppSubempreiteirosRoute
  AppOrcamentosDecomposicaoRoute: typeof AppOrcamentosDecomposicaoRoute
  AppOrcamentosIndexRoute: typeof AppOrcamentosIndexRoute
  AppOrcamentosIdDecomposicaoRoute: typeof AppOrcamentosIdDecomposicaoRoute
  AppOrcamentosIdIndexRoute: typeof AppOrcamentosIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBibliotecaRoute: AppBibliotecaRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDecomposicaoPrecosRoute: AppDecomposicaoPrecosRoute,
  AppDocumentosRoute: AppDocumentosRoute,
  AppObrasRoute: AppObrasRoute,
  AppSubempreiteirosRoute: AppSubempreiteirosRoute,
  AppOrcamentosDecomposicaoRoute: AppOrcamentosDecomposicaoRoute,
  AppOrcamentosIndexRoute: AppOrcamentosIndexRoute,
  AppOrcamentosIdDecomposicaoRoute: AppOrcamentosIdDecomposicaoRoute,
  AppOrcamentosIdIndexRoute: AppOrcamentosIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
